name: Pull Request

on:
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --coverage.reporter cobertura

      - name: Code Coverage Report
        if: startsWith(matrix.node-version, steps.node.outputs.node-version)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          # fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        if: startsWith(steps.node.outputs.node-version, matrix.node-version)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
