name: Pull Request

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: pull-request-${{ github.event.pull_request.number }}

jobs:
  cache:
    uses: ./.github/workflows/cache.yml

  test:
    name: Test
    needs: [cache]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Find Node.js Dev Version
        id: node-dev
        run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ needs.cache.outputs.yarn-cache-key }}
          path: ${{ needs.cache.outputs.yarn-cache-path }}

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --coverage.reporter cobertura

      - name: Code Coverage Report
        if: startsWith(steps.node-dev.outputs.node-version, matrix.node-version)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          # fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        if: startsWith(steps.node-dev.outputs.node-version, matrix.node-version)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
